save state and color in cookie
Hesammousavi/PersianAdminLTE pull request #7
Opened 2020-04-14 10:30 UTC by mohammadgh1370

save sidebar menu state (open or close) in cookie and save color theme in cookie

2022-10-30 04:27 UTC, merged

2022-10-30 04:27 UTC, Hesammousavi commented
thanks for your PR

2025-10-12 01:14 UTC, mahiwx reviewed
@mahanemoni

2025-10-12 01:17 UTC, mahiwx requested changes

2025-10-12 01:17 UTC, mahiwx commented on dist/js/demo.js
[](<https://t.me/mahan_vr.com>)*send.massage&repaley*on*t.me/e.m